from .models import (
    Actividad,
    AlertaProyecto,
    Asignacion,
    Colaborador,
    CuentaCobro,
    Modulo,
    Obligacion,
    Procedimiento,
    Proyecto,
    RiesgoProyecto,
    Rol,
)


TABLA_META = {
    "proyecto": {
        "modelo": Proyecto,
        "label": "Proyectos",
        "buscar_en": ["nombre", "objetivo", "responsable__nombre", "procedimiento__nombre"],
        "filtro_colaborador": False,
        "campos": [
            {"name": "nombre", "label": "Nombre", "type": "text", "required": True},
            {"name": "objetivo", "label": "Objetivo", "type": "textarea"},
            {
                "name": "estado",
                "label": "Estado",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "planeado", "label": "Planeado"},
                    {"id": "activo", "label": "Activo"},
                    {"id": "en_riesgo", "label": "En riesgo"},
                    {"id": "bloqueado", "label": "Bloqueado"},
                    {"id": "finalizado", "label": "Finalizado"},
                    {"id": "cancelado", "label": "Cancelado"},
                ],
            },
            {
                "name": "prioridad",
                "label": "Prioridad",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "baja", "label": "Baja"},
                    {"id": "media", "label": "Media"},
                    {"id": "alta", "label": "Alta"},
                    {"id": "critica", "label": "Crítica"},
                ],
            },
            {"name": "fecha_inicio", "label": "Fecha inicio", "type": "date"},
            {"name": "fecha_fin", "label": "Fecha fin", "type": "date"},
            {"name": "responsable_id", "label": "Responsable", "type": "fk", "fk_modelo": "Colaborador"},
            {"name": "procedimiento_id", "label": "Procedimiento", "type": "fk", "fk_modelo": "Procedimiento"},
            {"name": "presupuesto", "label": "Presupuesto / valor estimado", "type": "number"},
            {"name": "observaciones", "label": "Observaciones", "type": "textarea"},
        ],
        "columnas_lista": ["nombre", "estado", "prioridad", "responsable__nombre", "fecha_inicio", "fecha_fin", "presupuesto"],
    },
    "colaborador": {
        "modelo": Colaborador,
        "label": "Colaboradores",
        "buscar_en": ["nombre", "cedula"],
        "filtro_colaborador": False,
        "campos": [
            {"name": "nombre", "label": "Nombre completo", "type": "text", "required": True},
            {"name": "cedula", "label": "Cédula", "type": "text"},
            {"name": "procedimiento_id", "label": "Procedimiento", "type": "fk", "fk_modelo": "Procedimiento"},
            {"name": "fecha_inicio", "label": "Fecha inicio", "type": "date"},
            {"name": "fecha_fin", "label": "Fecha fin", "type": "date"},
            {"name": "honorarios", "label": "Honorarios", "type": "number"},
            {"name": "objeto", "label": "Objeto contrato", "type": "textarea"},
        ],
        "columnas_lista": ["nombre", "cedula", "procedimiento__nombre", "fecha_inicio", "fecha_fin", "honorarios"],
    },
    "obligacion": {
        "modelo": Obligacion,
        "label": "Obligaciones",
        "buscar_en": ["descripcion"],
        "filtro_colaborador": True,
        "campos": [
            {"name": "colaborador_id", "label": "Colaborador", "type": "fk", "required": True, "fk_modelo": "Colaborador"},
            {"name": "descripcion", "label": "Descripción", "type": "textarea", "required": True},
        ],
        "columnas_lista": ["colaborador__nombre", "descripcion"],
    },
    "actividad": {
        "modelo": Actividad,
        "label": "Actividades",
        "buscar_en": ["descripcion", "actividad_id"],
        "filtro_colaborador": True,
        "campos": [
            {"name": "obligacion_id", "label": "Obligación", "type": "fk", "required": True, "fk_modelo": "Obligacion"},
            {"name": "proyecto_id", "label": "Proyecto", "type": "fk", "fk_modelo": "Proyecto"},
            {"name": "actividad_id", "label": "ID actividad", "type": "text"},
            {"name": "descripcion", "label": "Descripción", "type": "textarea", "required": True},
            {"name": "fecha_inicio", "label": "Fecha inicio", "type": "date"},
            {"name": "fecha_fin", "label": "Fecha fin", "type": "date"},
            {"name": "progreso", "label": "Progreso (%)", "type": "number"},
            {
                "name": "estado",
                "label": "Estado",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "pendiente", "label": "Pendiente"},
                    {"id": "en_curso", "label": "En curso"},
                    {"id": "completada", "label": "Completada"},
                    {"id": "bloqueada", "label": "Bloqueada"},
                ],
            },
            {"name": "orden", "label": "Orden", "type": "number"},
        ],
        "columnas_lista": ["obligacion__colaborador__nombre", "proyecto__nombre", "actividad_id", "descripcion", "estado", "progreso"],
    },
    "cuenta_cobro": {
        "modelo": CuentaCobro,
        "label": "Cuentas de cobro",
        "buscar_en": ["numero_cuenta", "estado", "colaborador__nombre"],
        "filtro_colaborador": True,
        "campos": [
            {"name": "colaborador_id", "label": "Colaborador", "type": "fk", "required": True, "fk_modelo": "Colaborador"},
            {"name": "periodo", "label": "Periodo (día 1 del mes)", "type": "date", "required": True},
            {"name": "numero_cuenta", "label": "Número cuenta", "type": "text"},
            {"name": "fecha_radicacion", "label": "Fecha radicación", "type": "date"},
            {"name": "valor_cobrado", "label": "Valor cobrado", "type": "number", "required": True},
            {
                "name": "estado",
                "label": "Estado",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "borrador", "label": "Borrador"},
                    {"id": "radicada", "label": "Radicada"},
                    {"id": "aprobada", "label": "Aprobada"},
                    {"id": "pagada", "label": "Pagada"},
                    {"id": "rechazada", "label": "Rechazada"},
                ],
            },
            {"name": "observaciones", "label": "Observaciones", "type": "textarea"},
        ],
        "columnas_lista": ["colaborador__nombre", "periodo", "numero_cuenta", "valor_cobrado", "estado", "fecha_radicacion"],
    },
    "asignacion": {
        "modelo": Asignacion,
        "label": "Asignaciones",
        "buscar_en": [],
        "filtro_colaborador": False,
        "campos": [
            {"name": "colaborador_id", "label": "Colaborador", "type": "fk", "required": True, "fk_modelo": "Colaborador"},
            {"name": "rol_id", "label": "Rol", "type": "fk", "required": True, "fk_modelo": "Rol"},
            {"name": "modulo_id", "label": "Módulo", "type": "fk", "required": True, "fk_modelo": "Modulo"},
        ],
        "columnas_lista": ["colaborador__nombre", "rol__nombre", "modulo__nombre", "modulo__proyecto__nombre"],
    },
    "modulo": {
        "modelo": Modulo,
        "label": "Módulos",
        "buscar_en": ["nombre", "referente"],
        "filtro_colaborador": False,
        "campos": [
            {"name": "proyecto_id", "label": "Proyecto", "type": "fk", "required": True, "fk_modelo": "Proyecto"},
            {"name": "nombre", "label": "Nombre", "type": "text", "required": True},
            {"name": "referente", "label": "Referente", "type": "text"},
        ],
        "columnas_lista": ["nombre", "proyecto__nombre", "referente"],
    },
    "rol": {
        "modelo": Rol,
        "label": "Roles",
        "buscar_en": ["nombre"],
        "filtro_colaborador": False,
        "campos": [
            {"name": "nombre", "label": "Nombre", "type": "text", "required": True},
        ],
        "columnas_lista": ["nombre"],
    },
    "riesgo_proyecto": {
        "modelo": RiesgoProyecto,
        "label": "Riesgos de proyecto",
        "buscar_en": ["riesgo", "proyecto__nombre", "responsable__nombre"],
        "filtro_colaborador": False,
        "campos": [
            {"name": "proyecto_id", "label": "Proyecto", "type": "fk", "required": True, "fk_modelo": "Proyecto"},
            {"name": "riesgo", "label": "Riesgo", "type": "textarea", "required": True},
            {
                "name": "impacto",
                "label": "Impacto",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "bajo", "label": "Bajo"},
                    {"id": "medio", "label": "Medio"},
                    {"id": "alto", "label": "Alto"},
                    {"id": "critico", "label": "Crítico"},
                ],
            },
            {
                "name": "probabilidad",
                "label": "Probabilidad",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "bajo", "label": "Bajo"},
                    {"id": "medio", "label": "Medio"},
                    {"id": "alto", "label": "Alto"},
                    {"id": "critico", "label": "Crítico"},
                ],
            },
            {"name": "responsable_id", "label": "Responsable", "type": "fk", "fk_modelo": "Colaborador"},
            {"name": "fecha_limite", "label": "Fecha límite", "type": "date"},
            {
                "name": "estado",
                "label": "Estado",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "abierto", "label": "Abierto"},
                    {"id": "en_mitigacion", "label": "En mitigación"},
                    {"id": "cerrado", "label": "Cerrado"},
                ],
            },
            {"name": "plan_mitigacion", "label": "Plan de mitigación", "type": "textarea"},
        ],
        "columnas_lista": ["proyecto__nombre", "riesgo", "impacto", "probabilidad", "responsable__nombre", "fecha_limite", "estado"],
    },
    "alerta_proyecto": {
        "modelo": AlertaProyecto,
        "label": "Alertas de proyecto",
        "buscar_en": ["alerta", "proyecto__nombre", "responsable__nombre"],
        "filtro_colaborador": False,
        "campos": [
            {"name": "proyecto_id", "label": "Proyecto", "type": "fk", "required": True, "fk_modelo": "Proyecto"},
            {"name": "alerta", "label": "Alerta", "type": "textarea", "required": True},
            {
                "name": "severidad",
                "label": "Severidad",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "informativa", "label": "Informativa"},
                    {"id": "media", "label": "Media"},
                    {"id": "alta", "label": "Alta"},
                    {"id": "critica", "label": "Crítica"},
                ],
            },
            {"name": "responsable_id", "label": "Responsable", "type": "fk", "fk_modelo": "Colaborador"},
            {"name": "fecha_limite", "label": "Fecha límite", "type": "date"},
            {
                "name": "estado",
                "label": "Estado",
                "type": "choice",
                "opciones_fijas": [
                    {"id": "abierta", "label": "Abierta"},
                    {"id": "atendida", "label": "Atendida"},
                    {"id": "cerrada", "label": "Cerrada"},
                ],
            },
            {"name": "plan_accion", "label": "Plan de acción", "type": "textarea"},
        ],
        "columnas_lista": ["proyecto__nombre", "alerta", "severidad", "responsable__nombre", "fecha_limite", "estado"],
    },
}


FK_MODELOS = {
    "Procedimiento": Procedimiento,
    "Colaborador": Colaborador,
    "Proyecto": Proyecto,
    "RiesgoProyecto": RiesgoProyecto,
    "AlertaProyecto": AlertaProyecto,
    "Modulo": Modulo,
    "Rol": Rol,
    "Obligacion": Obligacion,
    "Actividad": Actividad,
    "CuentaCobro": CuentaCobro,
}
