# Generated by Django 6.0.3 on 2026-03-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_persona_cedula_persona_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
