# Generated by Django 6.0.3 on 2026-03-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_persona_procedimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(db_index=True, max_length=200)),
                ('obligacion', models.CharField(max_length=500)),
                ('actividad_id', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('progreso', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=20)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Actividad de Cronograma',
                'verbose_name_plural': 'Actividades de Cronograma',
                'ordering': ['colaborador', 'orden', 'fecha_inicio'],
            },
        ),
    ]
