# Generated by Django 6.0.3 on 2026-03-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cronogramaactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaactividad',
            name='semanas_activas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
