# Generated by Django 6.0.3 on 2026-04-15 16:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_refactor_erd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('periodo', models.DateField()),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_radicacion', models.DateField(blank=True, null=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('radicada', 'Radicada'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('rechazada', 'Rechazada')], default='radicada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cobro', to='dashboard.colaborador')),
            ],
            options={
                'verbose_name': 'Cuenta de cobro',
                'verbose_name_plural': 'Cuentas de cobro',
                'ordering': ['-periodo', 'colaborador__nombre'],
                'unique_together': {('colaborador', 'periodo')},
            },
        ),
    ]
