# Generated by Django 6.0.3 on 2026-04-23 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_actividad_evidencia_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='dashboard.actividad')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=10)),
                ('que_hizo', models.TextField(verbose_name='Que hizo esta semana')),
                ('impedimentos', models.TextField(blank=True, verbose_name='Impedimentos o bloqueos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_semanales', to='dashboard.colaborador')),
            ],
            options={
                'verbose_name': 'Reporte semanal',
                'verbose_name_plural': 'Reportes semanales',
                'ordering': ('-creado_en',),
                'unique_together': {('colaborador', 'semana')},
            },
        ),
    ]
