# Generated by Django 6.0.3 on 2026-07-24 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_gestion_proyectos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=250)),
                ('articulador', models.CharField(blank=True, max_length=200, null=True)),
                ('seyco', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_convenio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_suscripcion', models.DateField(blank=True, null=True)),
                ('fecha_terminacion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_modificatorios', models.CharField(blank=True, max_length=30, null=True)),
                ('contratista', models.CharField(blank=True, max_length=250, null=True)),
                ('clase_contrato', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('objeto', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('convenio', 'Convenio'), ('otra_modalidad', 'Otra modalidad')], default='convenio', max_length=20)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['tipo', 'entidad'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(db_index=True, max_length=30)),
                ('id_externo', models.CharField(blank=True, max_length=30, null=True)),
                ('cedula', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('nombre_contratista', models.CharField(max_length=200)),
                ('equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('ejecucion', 'Ejecución'), ('cesion', 'Cesión'), ('terminado', 'Terminado'), ('suspendido', 'Suspendido'), ('otro', 'Otro')], default='ejecucion', max_length=20)),
                ('modalidad', models.CharField(choices=[('unidad', 'Unidad'), ('adicion', 'Proyección/Adición')], default='unidad', max_length=20)),
                ('objeto', models.TextField(blank=True, null=True)),
                ('perfil_academico', models.CharField(blank=True, max_length=250, null=True)),
                ('cdp', models.CharField(blank=True, max_length=30, null=True)),
                ('rp', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('valor_honorarios', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_total_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('valor_cancelado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('saldo_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('porcentaje_ejecucion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ibc', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('importado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='dashboard.colaborador')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['equipo', 'nombre_contratista'],
                'unique_together': {('numero_contrato', 'modalidad')},
            },
        ),
        migrations.CreateModel(
            name='ContratoImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=500)),
                ('filas_leidas', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('sin_match_colaborador', models.PositiveIntegerField(default=0)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('origen', models.CharField(choices=[('cron', 'Cron'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_contratos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de importación de contratos',
                'verbose_name_plural': 'Logs de importación de contratos',
                'ordering': ['-ejecutado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado_secop', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='dashboard.contrato')),
            ],
            options={
                'verbose_name': 'Pago de contrato',
                'verbose_name_plural': 'Pagos de contrato',
                'ordering': ['contrato', 'mes'],
                'unique_together': {('contrato', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='SeguridadSocialContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aprobado', models.DateField(blank=True, null=True)),
                ('mes_cubierto', models.CharField(blank=True, max_length=20, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social', to='dashboard.contrato')),
            ],
            options={
                'verbose_name': 'Seguridad social de contrato',
                'verbose_name_plural': 'Seguridad social de contratos',
                'ordering': ['contrato', 'mes'],
                'unique_together': {('contrato', 'mes')},
            },
        ),
    ]
